language: java

sudo: false

jdk:
  - openjdk8

# before_script:

after_success:
  - mvn clean test jacoco:report coveralls:report

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE casbin;'
  - mysql -e "CREATE USER 'casbin_test'@'localhost' IDENTIFIED BY 'TEST_casbin';"
  - mysql -e "GRANT ALL ON casbin.* TO 'casbin_test'@'localhost';"